# 🚀 Day 1: Introduction to NumPy & Basics
✅ Install NumPy (pip install numpy)
✅ Import NumPy & Check Version
✅ Understanding ndarray (NumPy Array)
✅ Creating Arrays: array(), zeros(), ones(), full(), arange(), linspace()
✅ Checking Data Types: .dtype

✅ Shape and Size: .shape, .size, .ndim
✅ Basic Array Indexing & Slicing

📝 Practice: Create 1D, 2D, and 3D arrays and perform slicing.

In [5]:
# check version
import numpy as np
np.__version__


'1.26.4'

In [7]:
import numpy as np
x = [1,2,3,4,5]
y = np.array(x)
print(y)

# dimention of the array 
print(y.ndim)

[1 2 3 4 5]
1


In [50]:
# create array from user input
x = []
for i in range(1,6):
    user_input = input(f"enter value {i}: ")
    x.append(user_input)

print(np.array(x))



enter value 1:  11
enter value 2:  2
enter value 3:  3
enter value 4:  4
enter value 5:  5


['11' '2' '3' '4' '5']


In [62]:
# two dimentional array
arr  = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

print(arr.ndim)

# automating creating dimention

arn = np.array([1,2,3,4,5], ndmin = 10)
print(arn)
print(arn.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10


In [78]:
# create array using numpy function


In [80]:

#zeros arrays

arr_zero = np.zeros(4)
print(arr_zero)
print()
arr_zero2 = np.zeros((4,3))
print(arr_zero2)

[0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [90]:

#ones arrays

arr_ones = np.ones(4)
print(arr_ones)
print()
arr_ones2 = np.ones((4,3))
print(arr_ones2)

[1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [92]:
#empty arrays
arr_empty=  np.empty(4)
print(arr_empty)

[1. 1. 1. 1.]


In [104]:
#range arrays
arr_range=  np.arange(0,11)
print(arr_range)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [114]:
# array diagonal fills with 1's

arr_dia = np.eye(3,5)
print(arr_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [131]:
# linespace func

arr_linspace = np.linspace(0,20, 5)
print(arr_linspace)

[ 0.  5. 10. 15. 20.]


In [150]:
arr_type = np.array([[1,2,3,4,5]])
print(arr_type.dtype)

int64


# 🔥 Day 2: Array Operations & Broadcasting
✅ Arrays with Random Numbers
✅ Data types in NumPy arrays
✅ Arithmetic Operations: +, -, *, /, **
✅ Universal Functions (ufuncs): np.add(), np.subtract(), np.multiply(), np.divide(), np.mod(), np.reciprocal()
✅ Aggregation Functions: np.sum(), np.mean(), np.min(), np.max(), np.std(), np.sin(), np.cos()

✅ Element-wise operations
✅ Broadcasting Rules

📝 Practice: Try adding a scalar to a matrix and perform element-wise multiplication.

In [76]:
# Arrays with Random Numbers
a = np.random.rand(4)
print(a)

b = np.random.randn(3,4)
print()
print(b)

c = np.random.ranf(5)
print()
print(c)

# randint(min, max, total_value)
d = np.random.randint(0,10,10)
print()
print(d)


[0.80813601 0.48930516 0.28278312 0.71022454]

[[-0.19520521 -0.62231681 -0.30055305 -0.16247323]
 [-1.09074681 -0.34330969 -0.25892602  0.40201404]
 [-1.8709032   1.50476765  0.06455602  0.46512523]]

[0.95511008 0.78600689 0.97556485 0.66745471 0.53233635]

[2 3 4 6 4 6 7 2 8 7]


In [80]:
# Data types in NumPy arrays
x = np.array([1,2,3,4,5], dtype = np.int8)
print(x.dtype)

int8


In [88]:
# arithmetic operation

a= np.array([1,3,34,4,5])
b= np.array([1,2,3,4,5])
x= np.add(a,b)
print(x)

[ 2  5 37  8 10]


In [92]:
a = np.array([[1,2,3,4,5],[1,2,3,4,5]])
b = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(a)
print(b)
print()
print(np.add(a,b))


[[1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4 5]
 [1 2 3 4 5]]

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [138]:
# Aggregation Functions
a = np.array([[3,2,1],[3,4,5]])
b = np.array([[3,4,5],[3,4,5]])

print(np.min(a))
print(np.max(b))
print("position of a : ",np.argmin(a))
print()
a = np.array([[3,2,1],[3,4,5]])
print(np.min(a,  1))


1
5
position of a :  2

[1 3]


In [11]:
a = np.array([[3,2,1],[3,4,5]])
print(np.sqrt(a))


[[1.73205081 1.41421356 1.        ]
 [1.73205081 2.         2.23606798]]


In [142]:
x = np.array([1,2,3,4,5])
print(np.cumsum(x))

[ 1  3  6 10 15]


# 🔥 Day 3: Shape, Reshaping & Broadcasting
✅ Arrays with shape
✅ Convert 1D to MultiD,MultiD to 1D using reshape()
✅ Broadcasting In Numpy Arrays


In [23]:
# shape

var = np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(var)
print()
print(var.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]

(2, 5)


In [27]:
var1  = np.array([1,2,3,4,5], ndmin = 5)
print(var1)

print(var1.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


In [55]:
# reshape function

var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)
print()
x = var2.reshape(3,2)
print(x)
print(x.ndim)




[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [72]:
oneD = np.array([1,2,3,4,5,6])
print(oneD)
x = oneD.reshape(3,2)
print()
print(x)
print(x.ndim)

print(oneD.reshape(-1))
print(oneD.ndim)


[1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]
2
[1 2 3 4 5 6]
1


In [75]:
# # Broadcasting In Numpy Arrays
# The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.
# condition: 
# 1. dimention same
# 2. Dimension Padding
# 3. Shape Compatibility: Two dimensions are compatible if:
# They are equal, or
# One of them is 1.




In [79]:

array1 = np.array([1, 2, 3])
array2 = np.array([[1], [2], [3],[5]])
sum = array1 + array2

print(sum)

[[2 3 4]
 [3 4 5]
 [4 5 6]
 [6 7 8]]
