# 🚀 Day 1: Introduction to NumPy & Basics
✅ Install NumPy (pip install numpy)
✅ Import NumPy & Check Version
✅ Understanding ndarray (NumPy Array)
✅ Creating Arrays: array(), zeros(), ones(), full(), arange(), linspace()
✅ Checking Data Types: .dtype
✅ Shape and Size: .shape, .size, .ndim
✅ Basic Array Indexing & Slicing

📝 Practice: Create 1D, 2D, and 3D arrays and perform slicing.

In [37]:
# check version
import numpy as np
np.__version__


'1.26.4'

In [48]:
import numpy as np
x = [1,2,3,4,5]
y = np.array(x)
print(y)

# dimention of the array 
print(y.ndim)

[1 2 3 4 5]
1


In [50]:
# create array from user input
x = []
for i in range(1,6):
    user_input = input(f"enter value {i}: ")
    x.append(user_input)

print(np.array(x))



enter value 1:  11
enter value 2:  2
enter value 3:  3
enter value 4:  4
enter value 5:  5


['11' '2' '3' '4' '5']


In [62]:
# two dimentional array
arr  = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

print(arr.ndim)

# automating creating dimention

arn = np.array([1,2,3,4,5], ndmin = 10)
print(arn)
print(arn.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10
